logging.level.org.springframework.ai=DEBUG

spring.ai.azure.openai.api-key=TODO_set_me
spring.ai.azure.openai.endpoint=TODO_set_me

# Select the model to be used: azure-openai or ollama
spring.ai.model.chat=azure-openai
spring.ai.model.embedding=azure-openai

spring.ai.azure.openai.chat.options.deployment-name=gpt-5.1
spring.ai.azure.openai.embedding.options.deployment-name=embedding

# Install Ollama and download model, get it here: https://ollama.com/
spring.ai.ollama.chat.options.model=llama3.2

# Config for MCP Server
spring.ai.mcp.server.name=jira-message-generator
spring.ai.mcp.server.sse-endpoint=/sse
